### PR TITLE
Fixed GP Webpay response validation.

### PR DESCRIPTION
**Pull request by itsgoingd**
Hey, this PR fixes a few variable name typos in GP Webpay response validation and pubkey signature validation.

### CODE REVIEW

**Comment by palosopko** [comment]
Thanks for the changes.

**Comment by matuskopo** [comment]
In the latest release file 'src/Chaching/Encryption/PemKeys.php' has again that variable typos

**Comment by matuskopo** [comment]
The latest version with correct code was 0.17.5

**Comment by palosopko** [comment]
I am terribly sorry for the bug reappearing in the previous versions. Hopefully this fixes it, I also released a new version of v0.19.1. Thank you for your help.

**Pull request merged**
